django/week4/portfolio/portfolio/urls.py
from django.urls import path,include
from django.contrib import admin

from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('resume/', include('resume.urls', namespace='resume')),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),
    path('admin/', admin.site.urls),
]

django/week4/portfolio/resume/urls.py
from django.urls import path
from django.contrib import admin

from . import views

app_name='resume'
urlpatterns = [
    path('', views.home, name='home'),
]

django/week4/portfolio/resume/models.py
from django.db import models
from datetime import date
# Create your models here.

class Resume(models.Model):
    first_name=models.CharField(max_length=64, null=False, blank=False)
    last_name=models.CharField(max_length=64, null=False, blank=False)

    def get_full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def last_name_first_name(self):
        return "{}, {}".format(self.last_name, self.first_name)

    def get_experience(self):
        return self.experience_set.all()

    def get_education(self):
        return self.education_set.all()

class Experience(models.Model):
    parent_resume=models.ForeignKey(Resume, on_delete=models.CASCADE, default=1)
    title=models.CharField(max_length=64, null=True, blank=False)
    location=models.CharField(max_length=64, null=True, blank=False)
    start_date=models.DateField(blank=True, null=True)
    end_date=models.DateField(blank=True, null=True)
    description=models.CharField(max_length=256, null=False, blank= True)

    def __str__(self):
        return self.title


class Education(models.Model):
    parent_resume=models.ForeignKey(Resume, on_delete=models.CASCADE, default=1)
    institution_name=models.CharField(max_length=256, null=True, blank=False)
    location=models.CharField(max_length=64, null=True, blank=False)
    degree=models.CharField(max_length=64, null=True, blank=False)
    major=models.CharField(max_length=64, null=True, blank=False)
    gpa=models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.institution_name

django/week4/portfolio/portfolio/views.py
from django.shortcuts import render

def home(request):
    '''
    Returns home page
    '''
    context={'home':'active'}
    return render(request, 'home.html', context)

def portfolio(request):
    '''
    Returns resume page
    '''
    context={'portfolio':'active'}
    return render(request, 'portfolio.html', context)

def contact(request):
    '''
    Returns contact page
    '''
    context={'contact':'active'}
    return render(request, 'contact.html', context)

django/week4/portfolio/resume/views.py
from django.shortcuts import render
from .models import Resume, Education, Experience
# Create your views here.

def home(request):
    '''
    Renders home page from resume templates
    '''
    qsEx=Experience.objects.all()
    qsEdu=Education.objects.all()
    qsResume=Resume.objects.first()
    context={'education':qsEdu, 'experience':qsEx, 'resume':qsResume, 'res':'active'}
    return render(request, 'resume/home.html', context)

django/week4/portfolio/resume/templates/resume/home.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <link rel='stylesheet' href="{% static 'style.css' %}" />
  </head>
  <body>
    <div class="container">
    <div class="menu">
    <center><h1 id="logo">Portfolio</h1></center>
      <ul>
        <li><a class="{{ home }}" href="{% url 'home' %}">Home</a></li>
        <li><a class="{{ res }}" href="">Resume</a></li>
        <li><a class="{{ portfolio }}" href="{% url 'portfolio' %}">Portfolio</a></li>
        <li><a class="{{ contact }}" href="{% url 'contact' %}">Contact</a></li>
      </ul>
    </div>
    <div class="content">
        {% if resume %}
            <center><h3>Education</h3></center>
            {% for edu in education %}
              <h4>{{edu.institution_name}}-{{edu.location}}</h5>
              <p>{{edu.degree}}-{{edu.major}}, GPA: {{edu.gpa}}</p>
            {% endfor %}
            <br>
            <center><h3>Experience</h3></center>
            {% for exp in experience %}
              <h4>{{exp.title}}- {{exp.location}}<span style="float:right">{{exp.start_date}}-{{exp.end_date}}</span></h5>
              <p>{{exp.description}}</p>
            {% endfor %}

        {% else %}
          <p>Sorry not found</p>
        {% endif %}
      <br>
      <br>
    </div>
    </div>
  </body>
</div>
</html>

django/week4/portfolio/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <link rel='stylesheet' href="{% static 'style.css' %}" />
  </head>
  <body>
    <div class="container">
    <div class="menu">
    <center><h1 id="logo">Portfolio</h1></center>
      <ul>
        <li><a class="{{ home }}" href="{% url 'home' %}">Home</a></li>
        <li><a class="{{ resume }}" href="{% url 'resume:home' %}">Resume</a></li>
        <li><a class="{{ portfolio }}" href="{% url 'portfolio' %}">Portfolio</a></li>
        <li><a class="{{ contact }}" href="{% url 'contact' %}">Contact</a></li>
      </ul>
    </div>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</div>
</html>

django/week4/portfolio/templates/contact.html
{% extends 'base.html' %}

{% block content %}
    <form>
      <div class="form">
      <label for="fname">First Name</label>
      <input type="text" id="fname" placeholder="Your name..">

      <br>
      <br>

      <label for="lname">Last Name</label>
      <input type="text" id="lname" placeholder="Your last name..">

      <br>
      <br>

      <label for="email">Email</label>
      <input type="email" id="email" placeholder="Your Email..">

      <br>
      <br>

      <label for="address">Address</label>
      <input type="text" id="address" placeholder="Your address..">

      <br>
      <br>

      <label for="subject">Subject</label>
      <textarea id="subject"  placeholder="Short description for contacting us.." style="height:200px"></textarea>
      <br>
      <br>
      <input type="submit" value="Submit">
      </div>
    </form>

{% endblock %}

django/week4/portfolio/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="content">
    <center><h1> Welcome to Portfolio !!!</h1></center>
    <br>
    <center><h3>Lab2</h3></center>
    <h5>Subject</h5>
    <p>Python and Django</p>
    <br>
    <h5>Purpose</h5>
    <p>Become familiar with template inheritance, static file management, and the path-view-template pattern in Django.</p>
    <br>
    <h5>Description</h5>
    <p> In this lab we will design a “portfolio” site for ourselves.
      The site will contain a home page, a resume page, a portfolio page, and contact form.
      In order to have a common look and feel across all pages, each page will extends a “base.html” page.</p>
  </div>
{% endblock %}

django/week4/portfolio/templates/portfolio.html
{% extends 'base.html' %}
{% block content %}
<div class="content">
  <center><h2>Projects done by Arjun !!</h2></center>
  <h3 style="padding-left:20px;">Patidar Cattle Feed Web App</h3>
  <ul>
    <li>It was a live project made in Microsoft .Net Platform while I was an intern.</li>
    <li>Microsoft SQL Server was used for storing and working with data on application.</li>
    <li>Used different google API's to add more functionality to the website.</li>
  </ul>
  <br>
  <h3 style="padding-left:20px;">UNH USAT Application</h3>
  <ul>
    <li>A live project made in Android platform as a graduate assistant at UNH</li>
    <li>Application is a part of research of one Prof. in Occupational Therapy department at UNH</li>
    <li>This is a data acquisition application, specifically to collect data from disabled people</li>
  </ul>
  <br>
  <h3 style="padding-left:20px;">Korteweg-de-Vries and Burger's Equation</h5>
  <ul>
    <li>Projects attempted by me were creation of 1-d representation of waves in water using mathematical equation given
      by Korteweg–de Vries, and Burger’s Equation which is fundamental Partial Differential Equation</li>
    <li>Adam’s Bashford method was the time integration technique used in these projects.</li>
    <li>Parallelized the code using Open MPI and the aim behind parallelizing was to see how it affects the performance.</li>
  </ul>
  <br>
  <br>
  <br>
  <br>
</div>
{% endblock %}

django/week4/portfolio/templates/resume.html
{% extends 'base.html' %}
{% block content %}
<div class="content">
  <h3>Education</h3>
  <hr>
  <h5>University of New Hampshire -Manchester, NH</h5>
  <p>Masters in Science in Information Technology</p>
  <h5>Marwadi University -Rajkot, Gujarat, India</h5>
  <p>Bachelor of Engineering - Computer Engineering</p>
  <br>
  <h3>Work Eexperience</h3>
  <hr>
  <h5><b>Vodafone India Services Private Limited</b> - Ahmedabad, Gujarat, India</h5>
  <p>Junior Executive</p>
  <ul>
      <li>Collaborated  in  a ten member team  to  organize  one  team  of  Supply  Chain  Management  department,
        gained complete visibility over the supplier’s practices to prevent organization from enterprise risks and fake transactions
        which can cause loss to the company.</li>
      <li>Operated Material Management module of one Enterprise Resource Planning software SAP and used different T-codes to fetch
        data such as Purchase Orders, Shopping Carts, Vendor Information. </li>
      <li>Applied analytical skills to process the data stored in Excel and SAP, and performed audits on the data processed
            by my other team members</li>
  </ul>
  <h5>Aisomex Consultancy Services-Rajkot, Gujarat, India</h5>
  <p>Intern</p>
  <ul>
    <li>Assisted in a live project and developed a web based billing application in Microsoft .NET Platform</li>
    <li>Microsoft SQL Server was used for storing and working with data on application</li>
    <li>Used different Google API’s to add more functionality to the website.</li>
  </ul>
  <br>
  <h3>Technical Skills</h3>
  <hr>
  <ul>
    <li>Programming Language such as C, C++, Java, Python, Microsoft .NET.</li>
    <li>Web development languages such as HTML, CSS, JavaScript.</li>
    <li>Proficiency with Microsoft Office, Understanding of Object Oriented Principles</li>
    <li>SAP</li>
  </ul>
  <br>
  <h3>Certificates</h3>
  <hr>
  <ul>
    <li>Oracle certificate for course completion in Database Design and Programming with SQL</li>
    <li>CCNA Module-1 and Module-2 certificate</li>
  </ul>
  <br>
  <h3>Additional Experience</h3>
  <hr>
  <ul>
    <li>Served as the help desk specialist at University of New Hampshire IT department, helped in troubleshooting
      issues such  as  network  connection,  software  installation  and assisted  in  creating/updating
      user  and technical  process documentation.</li>
    <li>Student supervisor and leader of other employees in running the award-
      winning dining hall, Holloway Commons at University of New Hampshire.</li>
  </ul>
</div>

{% endblock %}